# Generated by Django 5.0.4 on 2024-07-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="status",
            field=models.CharField(
                choices=[
                    ("INACTIVE", "Inactive"),
                    ("PAID_IN_FULL", "Paid in Full"),
                    ("IN_COLLECTION", "In Collection"),
                ],
                max_length=20,
            ),
        ),
    ]
